# NeoForge mod metadata
modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

authors="Huntersxy"

description='''
Block Dynamics: 实体冻结器（红石冻结/解冻生物）与繁殖限制。Entity Freezer & breeding limiter.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"